# Assignment 10 Question 3

## Sam Dash

3. [50] Write a Python program (Jupyter notebook) that uses the data mining algorithms provided in SciKit-Learn to build knowledge models using the given hmwk10.csv.

Briefly report on your observations and experiences.

In [1]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

In [3]:
df = pd.read_csv("hwk10.csv")
df.head()

A         B         C         D         E         F         G  H
0 -0.851789 -1.205610 -0.474291  0.313508 -0.452754 -0.381246 -1.414164  2
1 -2.243104  1.252614  0.118889 -0.569868 -1.536101  1.536289 -0.473938  2
2  1.096491 -0.736308  0.070911 -1.822606  1.662994  0.319114  2.321419  0
3  0.927066  2.737201  2.115261  1.826195  0.140160  0.758732  1.104514  2
4 -1.251867  0.147549  1.398634  0.418399  0.377142  0.911071  0.139122  1

(a) [5] Create a set of unseen data (5 to 20 tuples).

In [5]:
u = df.sample(10)
uX = u.drop(columns = ['H'])
uy = u['H']

X = df.drop(index=u.index.values,columns = ['H'])
y = df.drop(index=u.index.values)['H']

uy.values

array([1, 0, 2, 0, 0, 2, 1, 0, 0, 2], dtype=int64)

(b) [15] Build a multiple level perceptron classifier and use it to classify several unseen
data. Investigate the impact of number and size of hidden layers and the different
activation functions.

In [52]:
multi_level_perceptron = MLPClassifier(hidden_layer_sizes = (50, 140, 70, 7, 1), activation = 'relu')
multi_level_perceptron.fit(X,y)
multi_level_perceptron.predict(uX)

C:\Users\samda\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1], dtype=int64)

relu seems to be the most accurate activation.

(c) [15] Build a support vector classifier and use it to classify the same set of unseen data.
Investigate the effect of different types of kernel functions and their parameters

In [46]:
support_vector = svm.SVC(kernel='linear', degree = 4, gamma = 4/7)
support_vector.fit(X,y)
support_vector.predict(uX)

array([1, 0, 2, 0, 0, 1, 1, 0, 0, 2], dtype=int64)

Of the various kernels, linear is most accurate.

(d) [15] Build a K neighbors classifier and use it to classify the same set of unseen data.
Investigate the impact of the number of neighbors and the metrics.

In [28]:
k_neighbors = KNeighborsClassifier(n_neighbors = 2, weights = 'uniform')
k_neighbors.fit(X,y)
k_neighbors.predict(uX)

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 2], dtype=int64)

Accuracy does not seem to improve past n_neighbors = 2