# COMPUTER SCIENCE 4373/5473
# Assignment #2

## By Sam Dash

In this assignment, you will work individually to develop a program for the preprocessing data. You will use Python in Anaconda distribution to write a Jupyter notebook. Your
program will read data from the provided CSV file into a DataFrame. The data file has 6 columns:
A, B, C, D, E, and F, where A and B are categorical and the rest are numeric. Your program
will than solve the following problems and write output to a text file. All values in the output
should be formatted to have up to four (4) digits after the decimal point. Unless explicitly stated
otherwise, you should use packages such as pandas and numpy that come installed with Anaconda.
Submit your solution via BlackBoard Learn in a zipped file yourName-hwk02.zip, which contains
the notebook, additional library if any, and the input/output files.

In [2]:
import scipy as sp
import pandas as pd
import numpy as np
import math
from sklearn.decomposition import PCA

1. [20] (Data Reduction) Write a function that takes a DataFrame, a set of column names (of
numeric columns), and an integer p (less than the total number of columns in the table), and
use PCA method in Scikit-Learn (specifically, sklearn.decomposition.PCA) to reduce the set
of columns into p new columns. Apply this function to reduce the columns {C, D, E, F} into
two columns p1, and p2.

In [3]:
df = pd.read_csv(r'hwk01.csv', usecols=['C', 'D', 'E', 'F'])

In [6]:
p = int(input("Enter an integer that is less than the total number of columns: "))

Enter an integer that is less than the total number of columns: 2


In [11]:
pca = PCA(n_components=p)
pDataframe = pd.DataFrame(data = df)
pca.fit(pDataframe)
dfPCA = pca.components_

print(dfPCA)

[[-9.99999999e-01 -6.18645926e-06  5.17222251e-05 -1.22332768e-05]
 [ 5.17884704e-05 -5.97658041e-03  9.99979060e-01 -2.48129553e-03]]


2. [40] (Similarity and Distance) Prompt the user for a tuple, say p = (a1, b2, 515, −0.876, 6.4253, 45),
and perform the following tasks.

In [3]:
df = pd.read_csv(r'hwk01.csv')

In [13]:
pInput = input("Please enter a tuple: ")
#when typing negatives for tuple, be sure to use - from keyboard instead of copying from text in instructions
pList = pInput.split(",")
dfNew = pd.DataFrame([[pList[0], pList[1], float(pList[2]), float(pList[3]),
float(pList[4]), float(pList[5])]], columns = list('ABCDEF'))
df = df.append(dfNew, ignore_index=True, sort=False)

pList

Please enter a tuple: a1, b2, 515, -0.876, 6.4253, 45


['a1', ' b2', ' 515', ' -0.876', ' 6.4253', ' 45']

(2.a.) Print the row in the DataFrame that is the least dissimilar to p, where the dissimilarity is
measured by different types of distances, including the Euclidean distance, Manhattan
distance, supremum distance, and cosine similarity, using the set of columns C, D, E,
and F.

Euclidean distance:

In [54]:
dfCrop = df[['C', 'D', 'E', 'F']].copy()

for i in range(len(df) - 1):
    print (sp.spatial.distance.euclidean(dfCrop.iloc[1000], dfCrop.iloc[i]))

450.70297402452553
4827.213879683706
6750.133197198262
5272.18492537778
2374.440442305476
7490.101791983331
7352.129480118818
9442.069501903714
362.9646477123622
2918.2885847049893
5693.150099039856
768.5170421847083
7386.114544988207
109.74660628999737
5270.156847343727
7939.109915082903
3846.2041005623996
3067.2883871004647
2138.29474508376
95.10354295307299
9481.127198836553
2526.448898004352
482.92961828769364
3197.203028926053
140.5006069148235
247.34358303948648
6701.135382528675
5399.165189325589
3416.3661315200984
1823.469086000027
6838.118408256605
6488.09114878804
2046.531398242795
1365.7175594370592
7960.1142318831
9291.101489625722
4303.184299073055
140.0603932530716
1700.4727924193649
8770.080326527723
712.0503017713856
4647.132135556709
2303.281471295048
52.539742998924126
664.8234348665378
8616.097294390496
8718.106657766504
4662.279375692598
6000.141088215159
8077.073210193941
6275.159526955195
9389.081958509103
7668.133688304189
8626.08462764027
9304.109364989912
2124.

8630.092456505397
4360.235749804783
6087.12786590052
2468.331032948514
9401.106176603724
5765.163595416306
6450.181333531031
1377.4237054040684
4148.1397806200775
3583.2056210515475
252.69935623101918
8441.068586777514
8652.088348470968
2819.2644544511327
7411.098704127076
891.4773460973576
4694.167114009575
3208.2927662450616
6467.130658782628
1633.6082769440102
7989.130050148056
7748.096876745121
307.4460933466022
1516.6883515483087
9209.092359662174
3324.228786824499
8251.101997563585
7969.090139671717
6591.130942040892
120.83785905616077
2396.325900231073
8742.105917867764
458.8419044984583
1374.6851672332828
2856.20247257261
5261.152985186935
9215.079179657263
2446.3343622555703
8760.098500444778
224.23628017378218
72.22765126672653
4146.22323255179
932.6637175620955
1191.7032052206362
6839.12824571625
312.8939327315389
6070.133378189745
5876.111197380023
1912.3717080005183
375.7203664609083
9091.090728836703
6669.12613942315
1663.3898809505538
7931.117670513435
2674.231103167629


Manhattan distance:

In [15]:
for i in range(len(df) - 1):
    print (sp.spatial.distance.cityblock(dfCrop.iloc[1000], dfCrop.iloc[i]))

491.61726090473945
4890.391474149392
6798.353251096601
5319.870720796717
2434.5032644533226
7543.09093400425
7406.444869328436
9482.266378411205
407.153563215518
2961.290958490166
5750.349238274601
834.2413055266703
7430.485773112703
148.78603994582414
5324.024991286658
7991.675296047093
3892.7793730042495
3111.5382679644777
2180.07805299553
142.16227294523986
9547.881196466562
2591.554300687966
528.6673824607293
3234.5485674581328
182.3027560103996
301.8625474885314
6754.184925229191
5457.224470718378
3484.771841858277
1876.0007059683767
6893.779361043447
6528.648206272537
2111.033195161241
1415.3409731372985
8017.406918599435
9344.427907277794
4352.240789900008
198.90392419345605
1750.0449978416982
8819.51942696411
757.3866031738715
4684.353303592957
2347.339976175226
83.3118833318751
729.263758169981
8672.784233207933
8765.249993467714
4733.576996980961
6045.172788438143
8116.6332203676575
6331.372829688698
9433.654985212934
7731.376060928673
8668.06982802921
9366.293396274497
2172.

3424.2350342887535
383.4843703386702
1494.5797419331382
395.54175659259494
4252.599453134451
5462.048157073264
4168.524998889354
8068.76815091519
138.01701980570544
3183.458555382867
8170.165449510562
1372.5690821665683
9119.015018040656
7242.483534505921
4211.167278899374
7985.6944007204
7664.639054804825
189.91775458019453
6929.262184684603
812.9137956160964
8918.06621686188
3381.5023583213947
4715.3751955744
4458.605128481957
2183.0931644910715
6231.342939312595
8046.715027113075
3217.2010664136405
985.4016082993666
3248.2041486141893
6343.067025600215
2074.26146681242
6869.40434201975
2723.7577523856644
1328.1884306003349
3601.220031827746
2006.864969039817
3464.878416467494
1946.4216035083318
543.0847321919937
7296.0378197546215
5241.31632847825
3543.728322334352
8998.169814008892
1459.6572432151902
8889.709648558535
7871.877829594686
8575.230854381225
2131.76024731843
3330.25095205501
4066.6801087650015
2841.424403549535
204.81229056324378
3539.0102821862893
273.4234108747753
926

supremum distance:

In [16]:
for i in range(len(df) - 1):
    print (sp.spatial.distance.minkowski(dfCrop.iloc[1000], dfCrop.iloc[i], p=float('inf')))

449.0
4827.0
6750.0
5272.0
2374.0
7490.0
7352.0
9442.0
361.0
2918.0
5693.0
767.0
7386.0
102.0
5270.0
7939.0
3846.0
3067.0
2138.0
83.0
9481.0
2526.0
481.0
3197.0
134.0
243.0
6701.0
5399.0
3416.0
1823.0
6838.0
6488.0
2046.0
1365.0
7960.0
9291.0
4303.0
131.0
1700.0
8770.0
711.0
4647.0
2303.0
38.0
663.0
8616.0
8718.0
4662.0
6000.0
8077.0
6275.0
9389.0
7668.0
8626.0
9304.0
2124.0
6253.0
825.0
5654.0
5690.0
4531.0
3672.0
7333.0
7644.0
7784.0
3520.0
4217.0
4678.0
2210.0
4758.0
3983.0
7604.0
9005.0
3013.0
9296.0
5635.0
8410.0
6833.0
6506.0
1083.0
7805.0
1150.0
641.0
6908.0
5687.0
8950.0
190.0
6014.0
3585.0
1788.0
4058.0
5764.0
8272.0
9379.0
2002.0
1735.0
7291.0
9035.0
8729.0
6140.0
6524.0
4800.0
5494.0
2818.0
3490.0
2220.0
956.0
2430.0
6664.0
7483.0
5250.0
3477.0
8191.0
518.0
5631.0
4412.0
6113.0
4425.0
5927.0
6858.0
4021.0
4211.0
3065.0
7802.0
6512.0
2919.0
791.0
5817.0
3251.0
5056.0
7601.0
210.0
4940.0
4922.0
78.0
9212.0
2292.0
7595.0
7436.0
43.0
4525.0
7068.0
4115.0
939.0
5312.0
2800.0
6717

cosine similarity:

In [17]:
for i in range(len(df) - 1):
    print (sp.spatial.distance.cosine(dfCrop.iloc[1000], dfCrop.iloc[i]))

0.003276139472348283
0.003704798531697362
0.003837193807904371
0.003838663750959981
0.003749415426782532
0.0037475321856785815
0.003814600397139545
0.0037928488646652436
0.0030509884082642325
0.003750574407050511
0.0036884702495129096
0.0036574355217636745
0.0038252046313512755
0.00298484883645056
0.0037315694050158443
0.003798044998229
0.0037213326960521265
0.003774247747327264
0.0035066769175258194
0.003915690535978844
0.0038340312114711894
0.0036855842536271943
0.003632526370583089
0.0036465086257314594
0.003446975502663263
0.003785045291534783
0.0038347715012609918
0.0037288372368742273
0.0037616108088676103
0.003583205978395454
0.003704770907086097
0.0037201825733611527
0.003595206765626302
0.0037737695515180913
0.0037692523475656436
0.0038269467500676724
0.003735177227287223
0.005674845807258744
0.003580309769627976
0.003756610702216112
0.003399935798293119
0.0036912749076664086
0.003580577809580321
0.002519434585456004
0.003790211025692214
0.0037460959076281997
0.003843176396828

0.0037876647092562887
0.0037241287459649497
0.003507354424516218
0.0036809884695166994
0.003798605891888629
0.0038486555353812735
0.0037678824210880535
0.00347680727228028
0.0035859080224667217
0.0037791242428714122
0.003678153360400116
0.00371159725433734
0.003707716912328074
0.003730361287724304
0.0037450723078321646
0.0038039002417451506
0.003840727553777068
0.0038105721309533713
0.003645405238062005
0.0037612299089656576
0.00379961648953564
0.00381911294389925
0.003489156016794115
0.005718520595701215
0.0038276984888088172
0.003403348174385701
0.003751995479334025
0.0037928408949010617
0.0035392163374760033
0.0036788814876562714
0.0037671122347623376
0.0037891682500551527
0.003758201844783038
0.003752770622886148
0.0035798689457630095
0.003792074479950225
0.0034167036071267587
0.0037692221731576714
0.0038064515296510892
0.003841956191458662
0.004243609193976816
0.0037776280076303737
0.003786168589280825
0.0034487353769010465
0.0037211767740711332
0.003766916301340073
0.003774513401

0.003468663875239586
0.0038146645542842528
0.0037962668955855428
0.003749184247823556
0.003773542879396352
0.0035864495906943183
0.0036677175928029326
0.003750081984884246
0.003861635609675451
0.0038075888145254755
0.0036410149828929317
0.0037721837441244688
0.0038494496072959405
0.0038071578462499645
0.0037174550980623167
0.0037386950989857226
0.0035720702627624057
0.003652625081863814
0.003802450790109213
0.003832734356979395
0.0037254812781188917
0.003718895798293098
0.0036736878030856346
0.003829103503698361
0.0038202783686343
0.0038365869040032363
0.003797934219300192
0.003741633763393759
0.0037353299207879553
0.0036329342282660493
0.0038272492567155147
0.003800385333446177
0.003791692114113454
0.0037815581012995425
0.003844839336963113
0.0037543356029574593
0.0037606680017694405
0.002809058981427359
0.0037976025643353672
0.0037726305140266536
0.0036661044929342523
0.0036307617467430386
0.0037459301141105072
0.003782195507887609
0.0036402851302994588
0.0038866488869824245
0.003795

(2.b.) Normalize the data points by making the norm of each data point (under columns C,
D, E, and F) equal to 1. That is, scale the values in columns C, D, E, and F, so that,
for each row (c, d, e, f) we have sqrt((c^2)+(d^2)+(e^2)+(f^2)) = 1. Then, print the row in the
DataFrame that has the shortest Euclidean distances from the normalized point p.

In [30]:
for i in range(len(df) - 1):
    dfNorm = df[['C', 'D', 'E', 'F']].copy()
    normDenominator = math.sqrt(((df["C"].iloc[i])**2) + ((df["D"].iloc[i])**2) + ((df["E"].iloc[i])**2) + ((df["F"].iloc[i])**2))
    dfNorm["C"].iloc[i] = df["C"].iloc[i]/normDenominator
    dfNorm["D"].iloc[i] = df["D"].iloc[i]/normDenominator
    dfNorm["E"].iloc[i] = df["E"].iloc[i]/normDenominator
    dfNorm["F"].iloc[i] = df["F"].iloc[i]/normDenominator
    dfEuclideanNormalization = sp.spatial.distance.euclidean(dfNorm.iloc[1000], dfNorm.iloc[i])
    print(dfEuclideanNormalization)

516.0062339746007
516.0066634614792
516.0067961123625
516.0067975851433
516.006708164517
516.00670627764
516.0067734753345
516.0067516818091
516.0060083885857
516.006709325735
516.0066471016706
516.00661600702
516.0067841000406
516.0059421212254
516.00669028404
516.0067568879743
516.0066800275667
516.0067330447803
516.0064649573003
516.0068747606232
516.0067929436607
516.0066442101024
516.0065910497724
516.0066050590257
516.0064051405895
516.0067438631704
516.0067936853796
516.0066875465969
516.0067203834443
516.0065416341447
516.0066634338011
516.0066788752235
516.0065536581053
516.0067325656612
516.0067280397362
516.0067858455226
516.006693898828
516.0086373086795
516.0065387323434
516.0067153736842
516.0063580100368
516.0066499117439
516.0065390009008
516.005475807506
516.0067490388775
516.0067048385889
516.0068021065009
516.006739471866
516.0067621523953
516.0067062052907
516.0067769616477
516.0067683004102
516.0067188427353
516.0067529611513
516.0067474932088
516.0064114255179
516

516.006793493411
516.0067732873425
516.0045860081877
516.0067668255367
516.0066631815388
516.0054188237891
516.0067387288873
516.0067653420372
516.0062563419181
516.0067975248598
516.0067420980747
516.0067503877474
516.0067818450647
516.0051827599295
516.0067464876452
516.0066828290152
516.0064656361158
516.0066396054448
516.0067574499508
516.006807596217
516.0067266671649
516.0064350299714
516.0065443414064
516.0067379306905
516.0066367648616
516.0066702733284
516.0066663854944
516.0066890735902
516.006703813013
516.0067627545218
516.0067996529305
516.0067694392915
516.0066039535076
516.0067200018091
516.0067584624995
516.006777996593
516.0064474025638
516.0086810676245
516.0067865987127
516.0063614290034
516.0067107495508
516.006751673824
516.0064975595577
516.0066374943947
516.0067258954915
516.0067479940888
516.0067169678987
516.006711526191
516.0065382906682
516.0067509059295
516.0063748102299
516.0067280095036
516.0067653107352
516.00680088394
516.0072033121762
516.0067364315667


516.005765991685
516.0067564446863
516.0067314244247
516.0066246927298
516.0065892817412
516.0067046724754
516.0067410078849
516.0065988235134
516.0068456629127
516.0067541086909
516.0066649626434
516.0066006028286
516.0063305877469
516.0062796107418
516.0067201036771
516.0066848316092
516.0067472501873
516.0067262527004
516.00675072637
516.0067299090421
516.0064153866448
516.0067456462367
516.0065647271565
516.0067419384364
516.0067231137813
516.0067312256424
516.0067460368574
516.0066351592593
516.0062516863701
516.0067661175617
516.0067434032246
516.0067190519796
516.0066191297145
516.0067694768205
516.006503077717
516.0067179203327
516.0067453940325
516.0067064859439
516.006697775749
516.0068081009395
516.0066090233089
516.0067066051357
516.0067138230522
516.0067896073465
516.0066565149514
516.0066309127986
516.006179363886
516.0065703647072
516.0067787521269
516.0067617080448
516.006726514462
516.0069242055306
516.0109512548289
516.0066158901906
516.0067370372516
516.0067605233363

3. [40] (Correlation) For this question, you will need to use packages scipy.stats

(3.a.) Compute the covariance and the correlation coefficient for each pair of the numeric
columns.

In [12]:
df = pd.read_csv(r'hwk01.csv')

Covariance:

In [13]:
np.cov(df['C'], df['D'])

array([[8.14588136e+06, 5.03941255e+01],
       [5.03941255e+01, 1.00317902e+00]])

In [14]:
np.cov(df['E'], df['F'])

array([[101.01134056,  -0.23126173],
       [ -0.23126173,   9.74734735]])

In [15]:
np.cov(df['C'], df['F'])

array([[8.14588136e+06, 9.96506907e+01],
       [9.96506907e+01, 9.74734735e+00]])

In [16]:
np.cov(df['D'], df['F'])

array([[1.00317902, 0.05236939],
       [0.05236939, 9.74734735]])

Correlation coefficients:

In [17]:
sp.stats.pearsonr(df['C'], df['D'])

(0.017628755433188648, 0.5776529976140807)

In [18]:
sp.stats.pearsonr(df['E'], df['F'])

(-0.007370135643236123, 0.8159354928166058)

In [19]:
sp.stats.pearsonr(df['C'], df['F'])

(0.011183250466705893, 0.7239278893263257)

In [20]:
sp.stats.pearsonr(df['D'], df['F'])

(0.01674731021419093, 0.5968254497841157)

(3.b.) Use the crosstab() function to construct the contingency table for columns A and B,
similar to the following sample, where the distinct values in attribute A are {a1, a2, a3}
and in attribute B are {b1, b2,} (this is just a sample and may not be the same as
the data in your data file). Write a sequence of Python code to perform the Pearson’s
chi-square (χ2) test of independence with a confidence level of 0.001 to determine if
the two attributes are correlated. You should use stats.chi2() to get the χ2 distribution.
Print sufficient information to report the result of the test.

In [21]:
df = pd.read_csv(r'hwk01.csv', usecols=['A', 'B'])

In [22]:
chi2TestResult = sp.stats.chi2_contingency(pd.crosstab(index=df['A'],columns=df['B']))
print (chi2TestResult)
if (chi2TestResult[1] >= .001):
    print ("Result is greater than confidence level of .001, therefore the two attributes are correlated.")
else:
    print ("Result is less than confidence level of .001, therefore the two attributes are not correlated.")

(13.46328505218233, 0.001192572517069232, 2, array([[180.846, 125.154],
       [189.711, 131.289],
       [220.443, 152.557]]))
Result is greater than confidence level of .001, therefore the two attributes are correlated.
